version: '3.8'

services:
  # service name
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "5000:5000"
    logging:
      driver: awslogs
      options:
        awslogs-group: nginx-logs
        awslogs-stream: nginx-log-stream
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - frontend
    restart: always
    networks:
      - net

  backend:
    image: akkassingh/ci-cd-backend:v1.0.${IMAGE_TAG}
    # container_name: backend

    env_file: ./.env
    environment:
      - MONGODB_URL=$MONGODB_URL
    depends_on:
      - mongodb
    logging:
      driver: awslogs
      options:
        awslogs-group: nginx-logs
        awslogs-stream: nginx-log-stream  
    restart: always
    networks:
      - net

  frontend:
    image: akkassingh/ci-cd-frontend:v1.0.${IMAGE_TAG}
    # container_name: frontend

    depends_on:
      - backend
    logging:
      driver: awslogs
      options:
        awslogs-group: nginx-logs
        awslogs-stream: nginx-log-stream
    restart: always
    networks:
      - net

  # Database service
  mongodb:
    image: mongo:latest
    # container_name: mongodb

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

    volumes:
      - ./../mydata:/data/db

    networks:
      - net

# Volumes define
volumes: 
  mydata:

networks:
  net:
    external: true